services:
  userservice.api:
    image: ${DOCKER_REGISTRY-}userserviceapi
    build:
      context: .
      dockerfile: src/UserService/UserService.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mssql_db,1433;Database=NutritionUserDb;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;
      - GrpcServices__MealPlanServiceUrl=https://mealplanservice.api:7132
    ports:
      - "7075:7075"
    depends_on:
      mssql_db:
        condition: service_healthy

  mealplanservice.api:
    image: ${DOCKER_REGISTRY-}mealplanserviceapi
    build:
      context: .
      dockerfile: src/MealPlanService/MealPlanService.API/Dockerfile
    environment:
      - ConnectionStrings__ConnectionURI=mongodb://mongodb:27017
      - GrpcServices__UserServiceUrl=https://userservice.api:7075
    ports:
      - "7132:7132"
    depends_on:
      mongodb:
        condition: service_healthy

  foodservice.api:
    image: ${DOCKER_REGISTRY-}foodserviceapi
    build:
      context: .
      dockerfile: src/FoodService/FoodService.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mssql_db,1433;Database=NutritionFoodDb;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;
      - Redis__Url=redis:6379
      - Redis__Database=1
      - GrpcServices__UserServiceUrl=https://userservice.api:7075
    ports:
      - "7022:7022"
    depends_on:
      mssql_db:
        condition: service_healthy
      redis:
        condition: service_healthy

  postservice.api:
    image: ${DOCKER_REGISTRY-}postserviceapi
    build:
      context: .
      dockerfile: src/PostService/PostService.API/Dockerfile
    environment:
      - ConnectionStrings__ConnectionURI=mongodb://mongodb:27017
      - Redis__Url=redis:6379
      - Redis__Database=0 
      - GrpcServices__UserServiceUrl=https://userservice.api:7075
    ports:
      - "7063:7063"
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy

  mssql_db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1434:1433"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "YourStrong!Passw0rd", "-C", "-Q", "SELECT 1"]
      interval: 10s
      retries: 10
      start_period: 5s
    volumes:
      - mssql_data:/var/opt/mssql

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27018:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongodb://localhost:27017 --quiet
      interval: 5s
      retries: 5
      start_period: 2s
    volumes:
      - mongodb_data:/data/db

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./src/nginx/certs/:/etc/nginx/ssl/
    depends_on:
      - userservice.api
      - mealplanservice.api
      - foodservice.api
      - postservice.api

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 5
      start_period: 2s

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      retries: 5
      start_period: 5s


volumes:
  mssql_data:
  mongodb_data:
